[SQUASH] raphael: switch to CustomDoze
doze: Add service for using proximity sensor for wake-up

* Added custom service that uses proximity sensor in wake-up mode
  to trigger display on.
* If more sensor triggers are suitable to use, they can be added
  to the service.

Change-Id: Id0849fb5c17ff569d771a19cebfc579dc93dbc48

Doze: Set gesture to disabled by default

Change-Id: I0bf3f6a3a4c01bab7ff7522e916e2149f9cfe8d5

doze: Consolidate Doze settings

* Allow user to disable ambient display from gesture panel
* Disable/enable doze settings based on ambient display state

Change-Id: I0ff7686ccc04037b3ada9a8355384ba6746cf30c

doze: Fix defaults

Change all defaults to false.

Change-Id: I2df507b2fc823d3fb07bce89d44067db565a5ab8

doze: Add back button to action bar

Change-Id: Ia56183c8c2d5a6bc25c84f1d1b9823b84bc936c9

doze: Add proximity wake

Change-Id: Ib02f4611e7b8bc09d540ca5c49aab68ef27f188b

doze: Restore proximity wake preference on boot

Change-Id: I614772d6ff1005968a7f8f1ed0349e3878ddadf1

doze: Prevent a PM wakeup with a timestamp in the future

Prevents:

java.lang.IllegalArgumentException: event time must not be in the future
at android.os.Parcel.readException(Parcel.java:1550)
        at android.os.Parcel.readException(Parcel.java:1499)
        at android.os.IPowerManager$Stub$Proxy.wakeUp(IPowerManager.java:550)
        at android.os.PowerManager.wakeUp(PowerManager.java:666)
        at com.cyanogenmod.settings.device.SamsungDozeService$SamsungProximitySensor.shouldPulse(SamsungDozeService.java:95)
        at com.cyanogenmod.settings.device.SamsungDozeService$SamsungProximitySensor.onSensorChanged(SamsungDozeService.java:75)
        at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:405)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:143)
        at android.os.Looper.loop(Looper.java:122)
        at android.app.ActivityThread.main(ActivityThread.java:5289)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

Change-Id: I8ed248271d67216e531b124bf27101fa538f1195
Signed-off-by: Brandon McAnsh <brandon.mcansh@gmail.com>

doze: Properly fix future timestamp error

Previously attempted fix at review.cyanogenmod.org/#/c/104083/
The timestamp isn't in the future, that would be impossible.
The real issue is the timestamp from the SensorEvent is a true
timestamp, the System.nanoTime is nanoseconds since boot.
So the previous patch would always return false and never pulse.
I've simply changed it so that the wakeup call gets sent the current
System.nanoTime in milliseconds since boot so it does not think the
event came from the future since the wakeUp method expects
uptimeMillis, not true world time.

Change-Id: I78f5e9d61107caf9c3bf6c10fa7c5bb400082294

doze: Fix typo

Change-Id: Id7716387688080b5ce0a99a4d968e210d8eed6f9

doze: ScreenType utility from CM SDK

Change-Id: I73b610bc71bf07b2fdedb1d5c5931e90f1e6de0f

doze: Remove summary for Doze

* Doesn't look good.

Change-Id: Id7716387688080b5ce0a99a4d968e210d8eed6f8

doze: Refactoring for the Xiaomi devices

Change-Id: I73b610bc71bf07b2fdedb1d5c5931e90f9e9de0f

doze: Doze improvements

* restructure the app
* add a tilt sensor from hammerhead-caf with an option to enable/disable
* add a one time dialog on first start to help users understand how the app works
* remove proximity wake up option and add an option to enable the sensors as soon as the screen turns off
* adjust and add new doze configs

Change-Id: Ia9d9a807d6c4f1a80a2ba8780e7486560f9a1d87

doze: Clean up doze

* Remove always enabled option.
* Use stock fade in delay.

Change-Id: Ieebf13f88c02d5036a09b5ef83ca1b53bd6771ac

doze: Further Refactoring, change theme to match Pixel

- Remove package from showing up in settings.

- Changed package name so we can do our own thing and not have it
get in the way of the Doze package currently used by Nick and others.

Change-Id: Ieebf13f88c02d5036a09b5ef83ca1b53bd6999ac

doze: Change package name for uniformity

With Android O we want to stick to just one package name for device specific doze.

- Set Doze package to compile.
- Enable bool to hide AOSP ambient display options.

Change-Id: I3279d0d3d06141f282a1135c9fb95f25e2fc994b

doze: Remove Doze dialog

We don't need this, nobody does. Most users are aware of ambient display and
what is capable of.

Change-Id: I30abd53cfae1101157b92bf9b869e6469915c2f2

doze: Change SDK to 27

This not only gets us inline with other packages we compile but fixes a
weird theme issue in that the navbar was black on black, black icons on
a black bar. We could of gone about this a different way by defining the
theme and calling it from the manifest but this is just easier :-)

Change-Id: I1fd191fe6991071bdfa278c704074b28c11cf1c1

doze: Change SDK to 29

Change-Id: Ibea87317edb015e4ecd763d03797e112f39ee44a

doze: Allow to enable Doze proximity actions without the notifications one

Change-Id: Iacb5573c3b66d2e33c67dbf9ddbedc66b7ffaef0

doze: Custom Doze service improvements

Don't start the service when all options are disabled or just
pulse on notification is enabled.

Start the service when enabling options only if it's not already running.

Change-Id: I07dab2e38b6701669dfe07d7154716de4b781609

doze: Fix CustomDoze receiver protected broadcast logspam

05-23 10:32:55.236   834 13503 E ActivityManager: Sending non-protected broadcast com.android.systemui.doze.pulse from system 1639:com.custom.ambient.display/1000 pkg com.custom.ambient.display
05-23 10:32:55.236   834 13503 E ActivityManager: java.lang.Throwable
05-23 10:32:55.236   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:19091)
05-23 10:32:55.236   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:19603)
05-23 10:32:55.236   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:19838)
05-23 10:32:55.236   834 13503 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:240)
05-23 10:32:55.236   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2922)
05-23 10:32:55.236   834 13503 E ActivityManager:       at android.os.Binder.execTransact(Binder.java:697)
05-23 10:32:55.243   834 13503 E ActivityManager: Sending non-protected broadcast com.android.systemui.doze.pulse from system 1639:com.custom.ambient.display/1000 pkg com.custom.ambient.display
05-23 10:32:55.243   834 13503 E ActivityManager: java.lang.Throwable
05-23 10:32:55.243   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:19091)
05-23 10:32:55.243   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:19696)
05-23 10:32:55.243   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:19838)
05-23 10:32:55.243   834 13503 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:240)
05-23 10:32:55.243   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2922)
05-23 10:32:55.243   834 13503 E ActivityManager:       at android.os.Binder.execTransact(Binder.java:697)

Change-Id: I132298a7acf246b8153019ce5a3f4129d9eeca4b

doze: Use ExecutorService to handle sensor listener

Maybe this is useless, but out of curiosity let's try what Google
did for SystemuUI here:
ezio84/abc_frameworks_base@fabc743

Registering a sensor seems to be an expensive operation, and we do it on each
screen-on event, so moving it to an asynchronous task looks like
a good idea anyway.

The interesting part about ExecutorService api:
By
moving all non-essential binder calls of the main thread or to the
next frame, we bring this down to 5ms, such that window animation
and Keyguard animation starts about at the same time.
https://developer.android.com/reference/java/util/concurrent/ExecutorService
Change-Id: Id33a200b68e2f313af4258c6109c7b80aa93329c

Change-Id: I1b38dbf9091ff056fad3e0e43a4232f8deadc7c7

doze: Respect RTL

- Add in a few null checks to prevent possible NPE's.
- Add missing INTERACT_ACROSS_USERS permission.

Change-Id: I4c4daf928f3298409d96309d86a333a222ad111f

doze: Set LOCAL_SDK_VERSION where possible

This change sets LOCAL_SDK_VERSION for all packages where
this is possible without breaking the build, and
LOCAL_PRIVATE_PLATFORM_APIS := true otherwise.

Setting one of these two will be made required soon, and this
is a change in preparation for that. Not setting LOCAL_SDK_VERSION
makes the app implicitly depend on the bootclasspath, which is
often not required. This change effectively makes depending on
private apis opt-in rather than opt-out.

Test: make relevant packages
Bug: 73535841

Change-Id: Ic906adbd670c4dbfe2cdf0b71cdbeaf9ac08a27e

doze: Change name to CustomDoze

Change-Id: I87d9f69175e35b4ac209f24eae7c9cdc9e62c46c

Migrate to blueprint where applicable

Change-Id: I898bc634e01d2ed6f133830762188e2fa6611978

CustomDoze: Change strings to match with Settings

Change-Id: I1e47baf929fddf1fbb822e58434d0bcb8f0f1687

Doze: Update DozeSettings to AndroidX

Change-Id: I9e38f3a6b099a4d4304f1612790238f0d564345f

Themes: Match custom options navbar with Settings

Change-Id: Ic684444c791a55b27832eb8b4d5ff84f4c8fe15b

Preference category: Match system theme

Change-Id: Iae433d01b9cbd25d68b0e6a97580e2fd2cac54a3

Correct doze typos

raphael: doze: Use Xiaomi tilt sensor

* Its faster apparently
[sashascurtu] : adapt for raphael

raphael: doze: Allow to wake the screen instead of pulsing

* based on https://github.com/nullxception/device_xiaomi_raphael/commit/17cfbf52e518e3f89a3d28b295f8d07526808097
[poad42]
	* simpler code stuff and adapt for our doze impl

Co-authored-by: Nauval Rizky <enuma.alrizky@gmail.com>